spring.application.name=spring-sec-demo

#Spring data source database url
spring.datasource.url=jdbc:mysql://localhost:3306/spring_boot

#username and password
spring.datasource.username=root
spring.datasource.password=password123

#Driver name
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Update table if necessary
spring.jpa.hibernate.ddl-auto=update
